# Generated by Django 3.2.16 on 2022-11-16 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role1',
            field=models.ManyToManyField(related_name='admin', related_query_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
