# Generated by Django 3.2.16 on 2022-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_role1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role1',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'Модератор'), ('U', 'Пользователь'), ('A', 'Админ')], default='U', max_length=1),
        ),
    ]
