# Generated by Django 3.2.16 on 2022-11-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221116_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=1, verbose_name='Биография'),
            preserve_default=False,
        ),
    ]
