# Generated by Django 3.2.16 on 2022-11-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Модератор'), ('user', 'Пользователь'), ('admin', 'Админ')], default='user', max_length=20),
        ),
    ]
