# Generated by Django 3.2.16 on 2022-11-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221118_1809'),
        ('reviews', '0006_auto_20221118_1954'),
    ]

    operations = [
    ]
