# Generated by Django 3.0 on 2022-11-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_title_rating'),
        ('reviews', '0007_merge_0006_auto_20221118_1809_0006_auto_20221118_1954'),
    ]

    operations = [
    ]
