# Generated by Django 3.0 on 2022-11-20 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20221119_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Оценка должна быть от 1 до 10!'), django.core.validators.MaxValueValidator(10, 'Оценка должна быть от 1 до 10!')], verbose_name='Оценка'),
        ),
    ]
